name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
    
    steps:
    - uses: actions/checkout@v3
    - name: Build
      id: compile
      run: |
            rustup target add x86_64-pc-windows-gnu
            cargo build --target x86_64-pc-windows-gnu --verbose
    - name: Run tests
      run: cargo test --verbose
